name: CI

on:
  push:
    branches: [ dev, feature/* ]
  pull_request:
    branches: [ dev ]

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v3
    
    - name: Setup Java
      uses: actions/setup-java@v3
      with:
        java-version: '17'
        distribution: 'temurin'
    
    - name: Compile
      run: javac *.java
    
    - name: Run CommandTests
      run: java CommandTests
      continue-on-error: false

    - name: Run ManagerTest
      run: java ManagerTest
      continue-on-error: false
    
    - name: Run UtilTests
      run: java UtilTests
      continue-on-error: false

    - name: Run ThreadTests
      run: java ThreadTests
      continue-on-error: false
